services:
  - type: web
    name: habit-tracker
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: gunicorn habit_tracker.wsgi:application --bind 0.0.0.0:8000
